# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    resolvers:
        default:
            web_path: ~
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets: # Contient la liste des filtres
        sizeOne: # Nom du filtre
            quality: 95 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                upscale:
                    min: [ 320,180 ]
                thumbnail:
                    size: [ 320,180 ]
                    mode: outbound

